### ISSUE TITLE
NonEmptyList.t broken when you update bs-platform

### ISSUE THREAD

**Issue by idkjs** [mlms13/bs-nonempty#4]
Studying your code, sir.

`NonEmptyList.t` does not tolerate updating the dependencies. Though obviously, it works with its oringal dependencies. 

Here is the error, if it matters to you:

```sh
:1
  
  1 │ open BsAbstract.Interface;
  2 │ 
  3 │ module ArrayMonoid: MONOID_ANY with type t('a) = array('a) = {
  4 │   type t('a) = array('a);
  5 │   let append = Array.append;
  6 │   let empty = [||];
  7 │ };
  8 │ 
  9 │ module ArrayArrayLike: NonEmptyBase.ARRAY_LIKE with type t('a) = array(
      'a) = {
  
  Signature mismatch:
  ...
  Values do not match:
    let empty: array('_weak1)
  is not included in
    let empty: t('a)
  File "/Users/mandalarian/Github/bs-nonempty/node_modules/bs-abstract/src/interfaces/Interface.re", line 23, characters 49-65:
    Expected declaration
  File "/Users/mandalarian/Github/bs-nonempty/src/NonEmptyArray.re", line 6, characters 6-11:
    Actual declaration
```
Tried to think through it but here I am asking so....
Thanks for sharing.

**Comment by mlms13** [comment]
Ah yes, we ran into the same issue in Relude as well. If you're looking for a usable implementation of `NonEmptyList` or `NonEmptyArray`, I'd definitely go for Relude's which is much better maintained these days than this library (and honestly, I should probably archive this repo).

However, if you're just interested in the theory behind how it's supposed to work and why it broke...

The core of `bs-nonempty` says that any structure (maybe it's a list, could be an array, etc) can be "nonempty" if you can guarantee a single value along with "the rest of the values" wrapped up in the underlying type. You can basically think of this as a tuple of `('a, t('a))` where `t` is a generic container type of your choosing. You can construct a `NonEmpty` where the container is `list` or `array` using module functors, which this library provides out of the box.

There are some common operations you might expect to perform on a nonempty structure, such as combining two of them, or constructing one from a single value. In order to be able to do these things, we need to be able to perform certain operations on the underlying structure. We use [Bastet](https://github.com/Risto-Stevcev/bastet) (at the time, it was `bs-abstract`) to define this behavior that the underlying structure has to conform to.

Specifically, if you want to join two nonempty values together, we need to know how to combine the underlying structure. And if you want to construct a nonempty from a single value, we need to know how to create an empty value of the underlying type. Turns out this is exactly what the `Monoid` type class does (see [fantasy-land](https://github.com/fantasyland/fantasy-land#monoid), [PureScript](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.Monoid#t:Monoid), or [Cats](https://typelevel.org/cats/typeclasses/monoid.html)). Bastet calls this `Monoid_Any` for container types like `list('a)` and `array('a)`. A Reason definition might look like:

```reason
module type Monoid_Any = {
  type t('a);
  let append: (t('a), t('a)) => t('a); // combine two together
  let empty: t('a);
}
```

Somewhere around Bucklescript 7.1, the type of `[||]` was changed from `array('a)` to `array('_weak)` to work around [an unsoundness issue with `Array.push`](https://github.com/rescript-lang/rescript-compiler/issues/4087). In OCaml, [weak polymorphism](https://caml.inria.fr/pub/docs/manual-ocaml/polymorphism.html#s:weak-polymorphism) is more restrictive than true polymorphism, and it means that `[||]` no longer conforms to the signature `t('a)`, so arrays no longer implement `Monoid_Any` (as well as similar type classes such as `Plus` that depend on being empty).

This [caused some pain in Bastet](https://github.com/Risto-Stevcev/bastet/issues/20) that led to arrays no longer working where `Monoid_Any` and `Plus` type classes are expected. Relude worked around this (if I remember correctly) by requiring a lazy definition of `empty: () => t('a)`. We could do the same here, but I'm probably just going to archive this repo in favor of Relude.

**Comment by idkjs** [comment]
Thank you, sir. This answer was worth the mere existence of this soon to be archived rep. Peace/love you to you, sir.
